Feature/use user cifs
Coda-Research-Group/AlphaFind pull request #13
Opened 2024-11-05 09:13 UTC by xcillik

2025-01-10 14:14 UTC, TerkaSlan requested changes

2025-01-10 14:14 UTC, TerkaSlan commented on ui/README.md
Can you add a section on how to send an API request with text / a file? :)

2025-01-15 14:26 UTC, ProchazkaDavid requested changes

2025-01-15 14:26 UTC, ProchazkaDavid commented on api/env/Dockerfile_local
> +    && chown -R user:user /home/user
Why is this index created when building the Docker image for API? Is it possible to do this during training?

2025-01-23 13:07 UTC, xcillik commented on api/env/Dockerfile_local
> +    && chown -R user:user /home/user
Building the index is not related to training the model. The index is used during the search process when USalign needs exact cifs/pdbs to compute scores. Therefore, it is better to store the code related to building the index here.

2025-01-24 10:37 UTC, TerkaSlan approved these changes

2025-01-24 13:45 UTC, ProchazkaDavid commented on api/env/Dockerfile_local
> +    && chown -R user:user /home/user
Oh, I see, we have a different view on the structure of the project. I would slightly prefer to do this within the training package, as I conceptually see that package as the place where all the indexes (LMI and supporting) are created/trained. The API package just uses them.

2025-01-24 13:48 UTC, ProchazkaDavid approved these changes
👍

2025-01-24 13:50 UTC, merged